/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TackRouteImport } from './routes/tack'
import { Route as ExempelrapportRouteImport } from './routes/exempelrapport'
import { Route as BestallRouteImport } from './routes/bestall'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPaymentWebhookRouteImport } from './routes/api/public/payment-webhook'

const TackRoute = TackRouteImport.update({
  id: '/tack',
  path: '/tack',
  getParentRoute: () => rootRouteImport,
} as any)
const ExempelrapportRoute = ExempelrapportRouteImport.update({
  id: '/exempelrapport',
  path: '/exempelrapport',
  getParentRoute: () => rootRouteImport,
} as any)
const BestallRoute = BestallRouteImport.update({
  id: '/bestall',
  path: '/bestall',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentWebhookRoute = ApiPublicPaymentWebhookRouteImport.update({
  id: '/api/public/payment-webhook',
  path: '/api/public/payment-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bestall': typeof BestallRoute
  '/exempelrapport': typeof ExempelrapportRoute
  '/tack': typeof TackRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bestall': typeof BestallRoute
  '/exempelrapport': typeof ExempelrapportRoute
  '/tack': typeof TackRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bestall': typeof BestallRoute
  '/exempelrapport': typeof ExempelrapportRoute
  '/tack': typeof TackRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bestall'
    | '/exempelrapport'
    | '/tack'
    | '/api/public/payment-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bestall'
    | '/exempelrapport'
    | '/tack'
    | '/api/public/payment-webhook'
  id:
    | '__root__'
    | '/'
    | '/bestall'
    | '/exempelrapport'
    | '/tack'
    | '/api/public/payment-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestallRoute: typeof BestallRoute
  ExempelrapportRoute: typeof ExempelrapportRoute
  TackRoute: typeof TackRoute
  ApiPublicPaymentWebhookRoute: typeof ApiPublicPaymentWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tack': {
      id: '/tack'
      path: '/tack'
      fullPath: '/tack'
      preLoaderRoute: typeof TackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exempelrapport': {
      id: '/exempelrapport'
      path: '/exempelrapport'
      fullPath: '/exempelrapport'
      preLoaderRoute: typeof ExempelrapportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestall': {
      id: '/bestall'
      path: '/bestall'
      fullPath: '/bestall'
      preLoaderRoute: typeof BestallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-webhook': {
      id: '/api/public/payment-webhook'
      path: '/api/public/payment-webhook'
      fullPath: '/api/public/payment-webhook'
      preLoaderRoute: typeof ApiPublicPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestallRoute: BestallRoute,
  ExempelrapportRoute: ExempelrapportRoute,
  TackRoute: TackRoute,
  ApiPublicPaymentWebhookRoute: ApiPublicPaymentWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
